require("dotenv").config();
const mongoose = require("mongoose");
const Location = require("../models/locations");

const unknownHours = {
  monday: { open: "", close: "", closed: false },
  tuesday: { open: "", close: "", closed: false },
  wednesday: { open: "", close: "", closed: false },
  thursday: { open: "", close: "", closed: false },
  friday: { open: "", close: "", closed: false },
  saturday: { open: "", close: "", closed: false },
  sunday: { open: "", close: "", closed: false },
};

const coalHarbourHours = {
  monday: { open: "09:00", close: "22:00", closed: false },
  tuesday: { open: "09:00", close: "22:00", closed: false },
  wednesday: { open: "09:00", close: "22:00", closed: false },
  thursday: { open: "09:00", close: "22:00", closed: false },
  friday: { open: "09:00", close: "21:00", closed: false },
  saturday: { open: "09:00", close: "17:00", closed: false },
  sunday: { open: "10:00", close: "17:00", closed: false },
};

const hastingsHours = {
  monday: { open: "09:00", close: "21:45", closed: false },
  tuesday: { open: "09:00", close: "21:45", closed: false },
  wednesday: { open: "09:00", close: "21:45", closed: false },
  thursday: { open: "09:00", close: "21:45", closed: false },
  friday: { open: "09:00", close: "21:45", closed: false },
  saturday: { open: "09:00", close: "16:45", closed: false },
  sunday: { open: "10:00", close: "14:00", closed: false },
};

const edmondsHours = {
  monday: { open: "06:00", close: "22:30", closed: false },
  tuesday: { open: "06:00", close: "22:30", closed: false },
  wednesday: { open: "06:00", close: "22:30", closed: false },
  thursday: { open: "06:00", close: "22:30", closed: false },
  friday: { open: "06:00", close: "22:30", closed: false },
  saturday: { open: "07:00", close: "21:00", closed: false },
  sunday: { open: "07:00", close: "21:00", closed: false },
};

const defaultLevels = {
  foodLevel: "unknown",
  waterLevel: "unknown",
  shelterLevel: "unknown",
  suppliesLevel: "unknown",
  status: "open",
  reports: [],
  timezone: "America/Vancouver",
};

const locations = [
  {
    name: "Coal Harbour Community Centre",
    address: "480 Broughton Street",
    city: "Vancouver",
    lat: 49.2907,
    lng: -123.1274,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "wifi",
      "charging stations",
      "community gathering",
      "fitness/recreation",
      "arts/culture",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "604-718-8222",
      email: "coalharbourcc@vancouver.ca",
      website: "https://vancouver.ca/parks-recreation-culture/coal-harbour-community-centre.aspx",
    },
    notes: "Real community centre. Hours and contact details are from the City of Vancouver page.",
    hours: coalHarbourHours,
  },
  {
    name: "Hastings Community Centre",
    address: "3096 East Hastings Street",
    city: "Vancouver",
    lat: 49.2811,
    lng: -123.0371,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "community gathering",
      "fitness/recreation",
      "youth programs",
      "senior programs",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "604-718-6222",
      email: "hastingscc@vancouver.ca",
      website: "https://vancouver.ca/parks-recreation-culture/hastings-community-centre.aspx",
    },
    notes: "Real community centre. Hours and contact details are from the City of Vancouver page.",
    hours: hastingsHours,
  },
  {
    name: "Kensington Community Centre",
    address: "5175 Dumfries Street",
    city: "Vancouver",
    lat: 49.2385,
    lng: -123.0741,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "community gathering",
      "fitness/recreation",
      "youth programs",
      "senior programs",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "604-718-6200",
      email: "kensingtoncc@vancouver.ca",
      website: "https://vancouver.ca/parks-recreation-culture/kensington-community-centre.aspx",
    },
    notes: "Real Vancouver community centre.",
    hours: unknownHours,
  },
  {
    name: "Mount Pleasant Community Centre",
    address: "1 Kingsway",
    city: "Vancouver",
    lat: 49.2635,
    lng: -123.0961,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "wifi",
      "community gathering",
      "fitness/recreation",
      "arts/culture",
      "youth programs",
      "senior programs",
      "newcomer support",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "604-257-3080",
      email: "",
      website: "https://vancouver.ca/parks-recreation-culture/community-and-cultural-centres.aspx",
    },
    notes: "Real Vancouver community centre.",
    hours: unknownHours,
  },
  {
    name: "Sunset Community Centre",
    address: "6810 Main Street",
    city: "Vancouver",
    lat: 49.2235,
    lng: -123.1013,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "community gathering",
      "fitness/recreation",
      "youth programs",
      "senior programs",
      "newcomer support",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "604-718-6505",
      email: "sunsetcc@vancouver.ca",
      website: "https://mysunset.net/facilities-rentals/community-centre/",
    },
    notes: "Real Vancouver community centre.",
    hours: unknownHours,
  },
  {
    name: "False Creek Community Centre",
    address: "1318 Cartwright Street",
    city: "Vancouver",
    lat: 49.2710,
    lng: -123.1352,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "community gathering",
      "fitness/recreation",
      "arts/culture",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "",
      email: "",
      website: "https://vancouver.ca/parks-recreation-culture/community-and-cultural-centres.aspx",
    },
    notes: "Real Vancouver community centre listed by the City of Vancouver.",
    hours: unknownHours,
  },
  {
    name: "Gathering Place Community Centre",
    address: "609 Helmcken Street",
    city: "Vancouver",
    lat: 49.2784,
    lng: -123.1247,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "low-cost meals",
      "community gathering",
      "arts/culture",
      "youth programs",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "604-665-2391",
      email: "",
      website: "https://vancouver.ca/parks-recreation-culture/community-and-cultural-centres.aspx",
    },
    notes: "Real Vancouver community centre. City page mentions a low-cost cafeteria and programs.",
    hours: unknownHours,
  },
  {
    name: "Carnegie Community Centre",
    address: "401 Main Street",
    city: "Vancouver",
    lat: 49.2814,
    lng: -123.1001,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "low-cost meals",
      "community gathering",
      "senior programs",
      "arts/culture",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "604-665-2220",
      email: "",
      website: "https://vancouver.ca/parks-recreation-culture/community-and-cultural-centres.aspx",
    },
    notes: "Real Vancouver community centre.",
    hours: unknownHours,
  },
  {
    name: "Roundhouse Community Arts & Recreation Centre",
    address: "181 Roundhouse Mews",
    city: "Vancouver",
    lat: 49.2735,
    lng: -123.1217,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "wifi",
      "community gathering",
      "fitness/recreation",
      "arts/culture",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "",
      email: "",
      website: "https://vancouver.ca/parks-recreation-culture/community-and-cultural-centres.aspx",
    },
    notes: "Real Vancouver community arts and recreation centre.",
    hours: unknownHours,
  },
  {
    name: "Hillcrest Community Centre",
    address: "4575 Clancy Loranger Way",
    city: "Vancouver",
    lat: 49.2445,
    lng: -123.1086,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "community gathering",
      "fitness/recreation",
      "youth programs",
      "senior programs",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "",
      email: "",
      website: "https://vancouver.ca/parks-recreation-culture/community-and-cultural-centres.aspx",
    },
    notes: "Real Vancouver community centre.",
    hours: unknownHours,
  },

  {
    name: "Greater Vancouver Food Bank Head Office",
    address: "8345 Winston Street",
    city: "Burnaby",
    lat: 49.2580,
    lng: -122.9236,
    type: "food bank",
    services: ["food", "information", "supplies", "accessibility support"],
    ...defaultLevels,
    contactInfo: {
      phone: "604-876-3601",
      email: "",
      website: "https://foodbank.bc.ca/find-food/locations/",
    },
    notes: "Real Greater Vancouver Food Bank head office. Check the official food bank website for current distribution locations and schedules.",
    hours: unknownHours,
  },
  {
    name: "Surrey Food Bank",
    address: "Unit 1 - 13478 78 Avenue",
    city: "Surrey",
    lat: 49.1451,
    lng: -122.8507,
    type: "food bank",
    services: ["food", "information", "supplies", "accessibility support"],
    ...defaultLevels,
    contactInfo: {
      phone: "604-581-5443",
      email: "info@surreyfoodbank.org",
      website: "https://surreyfoodbank.org/contact/",
    },
    notes: "Real Surrey Food Bank location and contact information.",
    hours: {
      monday: { open: "08:00", close: "16:00", closed: false },
      tuesday: { open: "08:00", close: "16:00", closed: false },
      wednesday: { open: "08:00", close: "16:00", closed: false },
      thursday: { open: "08:00", close: "16:00", closed: false },
      friday: { open: "08:00", close: "16:00", closed: false },
      saturday: { open: "", close: "", closed: true },
      sunday: { open: "", close: "", closed: true },
    },
  },
  {
    name: "North Vancouver Food Bank at North Shore Neighbourhood House",
    address: "225 East 2nd Street",
    city: "North Vancouver",
    lat: 49.3112,
    lng: -123.0757,
    type: "food bank",
    services: ["food", "information", "accessibility support"],
    ...defaultLevels,
    contactInfo: {
      phone: "604-876-3601",
      email: "",
      website: "https://www.nsnh.bc.ca/north-vancouver-food-bank/",
    },
    notes: "Real food distribution location. Official page says food is distributed at North Shore Neighbourhood House.",
    hours: unknownHours,
  },

  {
    name: "Edmonds Community Centre",
    address: "7433 Edmonds Street",
    city: "Burnaby",
    lat: 49.2181,
    lng: -122.9537,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "wifi",
      "charging stations",
      "community gathering",
      "fitness/recreation",
      "youth programs",
      "senior programs",
      "childcare",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "604-297-4838",
      email: "",
      website: "https://www.burnaby.ca/recreation-and-arts/recreation-facilities/edmonds-community-centre",
    },
    notes: "Real Burnaby community centre. Official page lists phone, address, and hours.",
    hours: edmondsHours,
  },
  {
    name: "Confederation Community Centre",
    address: "4585 Albert Street",
    city: "Burnaby",
    lat: 49.2796,
    lng: -123.0026,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "community gathering",
      "fitness/recreation",
      "senior programs",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "604-294-1936",
      email: "",
      website: "https://www.burnaby.ca/recreation-and-arts/recreation-facilities",
    },
    notes: "Real Burnaby community centre.",
    hours: unknownHours,
  },
  {
    name: "Bonsor Recreation Complex",
    address: "6550 Bonsor Avenue",
    city: "Burnaby",
    lat: 49.2257,
    lng: -122.9975,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "community gathering",
      "fitness/recreation",
      "senior programs",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "",
      email: "",
      website: "https://www.burnaby.ca/recreation-and-arts/recreation-facilities",
    },
    notes: "Real Burnaby recreation facility.",
    hours: unknownHours,
  },
  {
    name: "Cameron Recreation Complex",
    address: "9523 Cameron Street",
    city: "Burnaby",
    lat: 49.2549,
    lng: -122.8999,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "community gathering",
      "fitness/recreation",
      "senior programs",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "",
      email: "",
      website: "https://www.burnaby.ca/recreation-and-arts/recreation-facilities",
    },
    notes: "Real Burnaby recreation facility.",
    hours: unknownHours,
  },

  {
    name: "City Centre Community Centre",
    address: "5900 Minoru Boulevard",
    city: "Richmond",
    lat: 49.1713,
    lng: -123.1436,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "wifi",
      "community gathering",
      "fitness/recreation",
      "arts/culture",
      "youth programs",
      "senior programs",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "604-204-8588",
      email: "citycentre@richmond.ca",
      website: "https://www.richmond.ca/parks-recreation/centres/citycentre.htm",
    },
    notes: "Real Richmond community centre. Official page lists amenities and contact information.",
    hours: unknownHours,
  },
  {
    name: "South Arm Community Centre",
    address: "8880 Williams Road",
    city: "Richmond",
    lat: 49.1404,
    lng: -123.1267,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "community gathering",
      "fitness/recreation",
      "youth programs",
      "senior programs",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "604-238-8060",
      email: "southarm@richmond.ca",
      website: "https://www.richmond.ca/parks-recreation/centres/southarm.htm",
    },
    notes: "Real Richmond community centre. Official page lists contact information.",
    hours: unknownHours,
  },
  {
    name: "Steveston Community Centre",
    address: "4111 Moncton Street",
    city: "Richmond",
    lat: 49.1250,
    lng: -123.1817,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "community gathering",
      "fitness/recreation",
      "arts/culture",
      "youth programs",
      "senior programs",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "604-238-8094",
      email: "stevestoncc@richmond.ca",
      website: "https://www.richmond.ca/parks-recreation/centres/steveston.htm",
    },
    notes: "Real Richmond community centre. Official page lists contact information.",
    hours: unknownHours,
  },
  {
    name: "Minoru Centre for Active Living",
    address: "7191 Granville Avenue",
    city: "Richmond",
    lat: 49.1623,
    lng: -123.1450,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "community gathering",
      "fitness/recreation",
      "senior programs",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "604-233-6225",
      email: "minorucentre@richmond.ca",
      website: "https://minorucentre.ca/",
    },
    notes: "Real Richmond active living facility. Official page lists aquatic centre hours and facility information.",
    hours: {
      monday: { open: "06:00", close: "22:00", closed: false },
      tuesday: { open: "06:00", close: "22:00", closed: false },
      wednesday: { open: "06:00", close: "22:00", closed: false },
      thursday: { open: "06:00", close: "22:00", closed: false },
      friday: { open: "06:00", close: "22:00", closed: false },
      saturday: { open: "06:00", close: "22:00", closed: false },
      sunday: { open: "07:00", close: "21:00", closed: false },
    },
  },

  {
    name: "Guildford Recreation Centre",
    address: "15105 105 Avenue",
    city: "Surrey",
    lat: 49.1932,
    lng: -122.8045,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "community gathering",
      "fitness/recreation",
      "youth programs",
      "senior programs",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "",
      email: "",
      website: "https://www.surrey.ca/parks-recreation/recreation-facilities",
    },
    notes: "Real Surrey recreation facility.",
    hours: unknownHours,
  },
  {
    name: "Newton Recreation Centre",
    address: "13730 72 Avenue",
    city: "Surrey",
    lat: 49.1339,
    lng: -122.8401,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "community gathering",
      "fitness/recreation",
      "youth programs",
      "senior programs",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "",
      email: "",
      website: "https://www.surrey.ca/parks-recreation/recreation-facilities",
    },
    notes: "Real Surrey recreation facility.",
    hours: unknownHours,
  },
  {
    name: "North Surrey Sport & Ice Complex",
    address: "10950 126A Street",
    city: "Surrey",
    lat: 49.2026,
    lng: -122.8731,
    type: "community centre",
    services: [
      "information",
      "washrooms",
      "community gathering",
      "fitness/recreation",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "",
      email: "",
      website: "https://www.surrey.ca/parks-recreation/recreation-facilities",
    },
    notes: "Real Surrey recreation facility.",
    hours: unknownHours,
  },

  {
    name: "Directions Youth Services Centre",
    address: "1138 Burrard Street",
    city: "Vancouver",
    lat: 49.2801,
    lng: -123.1279,
    type: "emergency shelter",
    services: [
      "shelter",
      "food",
      "water",
      "showers",
      "laundry",
      "medical support",
      "youth programs",
      "information",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "604-633-1472",
      email: "",
      website: "https://www.fsgv.ca/find-support/youth-services/directions-youth-services/",
    },
    notes: "Real youth support service. Availability should be checked directly.",
    hours: unknownHours,
  },
  {
    name: "First United",
    address: "320 East Hastings Street",
    city: "Vancouver",
    lat: 49.2813,
    lng: -123.0972,
    type: "emergency shelter",
    services: [
      "shelter",
      "food",
      "water",
      "washrooms",
      "showers",
      "laundry",
      "supplies",
      "information",
      "accessibility support",
    ],
    ...defaultLevels,
    contactInfo: {
      phone: "604-681-8365",
      email: "",
      website: "https://firstunited.ca/",
    },
    notes: "Real Vancouver support organization. Current availability should be checked directly.",
    hours: unknownHours,
  },
  {
    name: "Vancouver Coastal Health - City Centre UPCC",
    address: "1290 Hornby Street",
    city: "Vancouver",
    lat: 49.2766,
    lng: -123.1290,
    type: "medical support",
    services: ["medical support", "information", "accessibility support"],
    ...defaultLevels,
    contactInfo: {
      phone: "604-416-1811",
      email: "",
      website: "https://www.vch.ca/",
    },
    notes: "Real urgent and primary care location. Call 911 for emergencies.",
    hours: unknownHours,
  },
  {
    name: "BC SPCA Vancouver Community Animal Centre",
    address: "1205 East 7th Avenue",
    city: "Vancouver",
    lat: 49.2645,
    lng: -123.0794,
    type: "pet support",
    services: ["pet support", "information", "supplies", "accessibility support"],
    ...defaultLevels,
    contactInfo: {
      phone: "604-879-7721",
      email: "",
      website: "https://spca.bc.ca/locations/vancouver/",
    },
    notes: "Real animal welfare location. Confirm emergency pet support availability directly.",
    hours: unknownHours,
  },
  {
    name: "TransLink Customer Service Centre - Waterfront Station",
    address: "601 West Cordova Street",
    city: "Vancouver",
    lat: 49.2856,
    lng: -123.1116,
    type: "information centre",
    services: ["information", "recovery information", "accessibility support"],
    ...defaultLevels,
    contactInfo: {
      phone: "604-953-3333",
      email: "",
      website: "https://www.translink.ca/",
    },
    notes: "Real transit information location. Useful for transportation updates during disruptions.",
    hours: unknownHours,
  },
  {
    name: "Surrey Food Bank - Main Depot",
    address: "Unit 1 - 13478 78 Avenue",
    city: "Surrey",
    lat: 49.1451,
    lng: -122.8507,
    type: "food bank",
    services: ["food", "information", "supplies", "accessibility support"],
    status: "open",
    foodLevel: "unknown",
    waterLevel: "unknown",
    shelterLevel: "unknown",
    suppliesLevel: "unknown",
    contactInfo: {
      phone: "604-581-5443",
      email: "info@surreyfoodbank.org",
      website: "https://surreyfoodbank.org/contact/"
    },
    notes: "Real Surrey Food Bank main depot. Food distribution hours should be checked on the official website before visiting.",
    reports: [],
    hours: {
      monday: { open: "09:00", close: "13:00", closed: false },
      tuesday: { open: "09:00", close: "13:00", closed: false },
      wednesday: { open: "", close: "", closed: true },
      thursday: { open: "09:00", close: "13:00", closed: false },
      friday: { open: "09:00", close: "13:00", closed: false },
      saturday: { open: "", close: "", closed: true },
      sunday: { open: "", close: "", closed: true }
    },
    timezone: "America/Vancouver"
  },
  {
    name: "Surrey Food Bank - Cloverdale Distribution",
    address: "5950 179 Street",
    city: "Surrey",
    lat: 49.1119,
    lng: -122.7266,
    type: "food bank",
    services: ["food", "information", "accessibility support"],
    status: "open",
    foodLevel: "unknown",
    waterLevel: "unknown",
    shelterLevel: "unknown",
    suppliesLevel: "unknown",
    contactInfo: {
      phone: "604-581-5443",
      email: "info@surreyfoodbank.org",
      website: "https://surreyfoodbank.org/about-us/alternate-distribution-centres/"
    },
    notes: "Real alternate Surrey Food Bank distribution site at Hillside Church. Distribution is listed as alternate Tuesdays from 10:00 AM to 12:00 PM.",
    reports: [],
    hours: {
      monday: { open: "", close: "", closed: true },
      tuesday: { open: "10:00", close: "12:00", closed: false },
      wednesday: { open: "", close: "", closed: true },
      thursday: { open: "", close: "", closed: true },
      friday: { open: "", close: "", closed: true },
      saturday: { open: "", close: "", closed: true },
      sunday: { open: "", close: "", closed: true }
    },
    timezone: "America/Vancouver"
  },
  {
    name: "Surrey Food Bank - North Delta Distribution",
    address: "11300 84 Avenue",
    city: "Delta",
    lat: 49.1555,
    lng: -122.9104,
    type: "food bank",
    services: ["food", "information", "accessibility support"],
    status: "open",
    foodLevel: "unknown",
    waterLevel: "unknown",
    shelterLevel: "unknown",
    suppliesLevel: "unknown",
    contactInfo: {
      phone: "604-581-5443",
      email: "info@surreyfoodbank.org",
      website: "https://surreyfoodbank.org/about-us/alternate-distribution-centres/"
    },
    notes: "Real alternate Surrey Food Bank distribution site at Northside Community Church. Distribution is listed as every 2nd Tuesday from 10:00 AM to 12:00 PM.",
    reports: [],
    hours: {
      monday: { open: "", close: "", closed: true },
      tuesday: { open: "10:00", close: "12:00", closed: false },
      wednesday: { open: "", close: "", closed: true },
      thursday: { open: "", close: "", closed: true },
      friday: { open: "", close: "", closed: true },
      saturday: { open: "", close: "", closed: true },
      sunday: { open: "", close: "", closed: true }
    },
    timezone: "America/Vancouver"
  },
  {
    name: "Surrey Food Bank - Guildford/Whalley Distribution",
    address: "10330 144 Street",
    city: "Surrey",
    lat: 49.1902,
    lng: -122.8219,
    type: "food bank",
    services: ["food", "information", "accessibility support"],
    status: "open",
    foodLevel: "unknown",
    waterLevel: "unknown",
    shelterLevel: "unknown",
    suppliesLevel: "unknown",
    contactInfo: {
      phone: "604-581-5443",
      email: "info@surreyfoodbank.org",
      website: "https://surreyfoodbank.org/about-us/alternate-distribution-centres/"
    },
    notes: "Real alternate Surrey Food Bank distribution site at Cedar Grove Baptist Church. Distribution is listed as every 2nd Wednesday from 10:00 AM to 12:30 PM.",
    reports: [],
    hours: {
      monday: { open: "", close: "", closed: true },
      tuesday: { open: "", close: "", closed: true },
      wednesday: { open: "10:00", close: "12:30", closed: false },
      thursday: { open: "", close: "", closed: true },
      friday: { open: "", close: "", closed: true },
      saturday: { open: "", close: "", closed: true },
      sunday: { open: "", close: "", closed: true }
    },
    timezone: "America/Vancouver"
  },
  {
    name: "North Vancouver Food Bank at North Shore Neighbourhood House",
    address: "225 East 2nd Street",
    city: "North Vancouver",
    lat: 49.3112,
    lng: -123.0757,
    type: "food bank",
    services: ["food", "information", "accessibility support"],
    status: "open",
    foodLevel: "unknown",
    waterLevel: "unknown",
    shelterLevel: "unknown",
    suppliesLevel: "unknown",
    contactInfo: {
      phone: "604-876-3601",
      email: "",
      website: "https://www.nsnh.bc.ca/north-vancouver-food-bank/"
    },
    notes: "Real North Vancouver food bank distribution location. Official page says distribution is at North Shore Neighbourhood House on Wednesdays from 9:00 AM to 6:00 PM, with current calendar through GVFB.",
    reports: [],
    hours: {
      monday: { open: "", close: "", closed: true },
      tuesday: { open: "", close: "", closed: true },
      wednesday: { open: "09:00", close: "18:00", closed: false },
      thursday: { open: "", close: "", closed: true },
      friday: { open: "", close: "", closed: true },
      saturday: { open: "", close: "", closed: true },
      sunday: { open: "", close: "", closed: true }
    },
    timezone: "America/Vancouver"
  },
  {
    name: "Greater Vancouver Food Bank",
    address: "8345 Winston Street",
    city: "Burnaby",
    lat: 49.2580,
    lng: -122.9236,
    type: "food bank",
    services: ["food", "information", "supplies", "accessibility support"],
    status: "open",
    foodLevel: "unknown",
    waterLevel: "unknown",
    shelterLevel: "unknown",
    suppliesLevel: "unknown",
    contactInfo: {
      phone: "604-876-3601",
      email: "",
      website: "https://foodbank.bc.ca/find-food/locations/"
    },
    notes: "Real Greater Vancouver Food Bank location. GVFB provides food through distribution locations across Vancouver, Burnaby, New Westminster, and the North Shore. Check official schedule before visiting.",
    reports: [],
    hours: {
      monday: { open: "", close: "", closed: false },
      tuesday: { open: "", close: "", closed: false },
      wednesday: { open: "", close: "", closed: false },
      thursday: { open: "", close: "", closed: false },
      friday: { open: "", close: "", closed: false },
      saturday: { open: "", close: "", closed: false },
      sunday: { open: "", close: "", closed: false }
    },
    timezone: "America/Vancouver"
  },
  {
    name: "Sources White Rock / South Surrey Food Bank",
    address: "2343 156 Street",
    city: "Surrey",
    lat: 49.0457,
    lng: -122.7925,
    type: "food bank",
    services: ["food", "information", "accessibility support"],
    status: "open",
    foodLevel: "unknown",
    waterLevel: "unknown",
    shelterLevel: "unknown",
    suppliesLevel: "unknown",
    contactInfo: {
      phone: "",
      email: "",
      website: "https://www.sourcesbc.ca/our-services/sources-white-rock-south-surrey-food-bank/"
    },
    notes: "Real Sources food bank program serving White Rock and South Surrey. Official page says it provides weekly support and mobile service for those who qualify.",
    reports: [],
    hours: {
      monday: { open: "", close: "", closed: false },
      tuesday: { open: "", close: "", closed: false },
      wednesday: { open: "", close: "", closed: false },
      thursday: { open: "", close: "", closed: false },
      friday: { open: "", close: "", closed: false },
      saturday: { open: "", close: "", closed: false },
      sunday: { open: "", close: "", closed: false }
    },
    timezone: "America/Vancouver"
  }
];

async function seedLocations() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);

    await Location.deleteMany({});
    await Location.insertMany(locations);

    console.log(`Seeded ${locations.length} locations successfully.`);
    process.exit(0);
  } catch (error) {
    console.error("Error seeding locations:", error);
    process.exit(1);
  }
}

seedLocations();